# Generated by Django 4.0.1 on 2022-02-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_bio_biografia_alter_blog_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='imagen',
            new_name='avatar',
        ),
    ]
