# Generated by Django 4.0.1 on 2022-02-12 15:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_remove_bio_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
